### ISSUE TITLE
Albian Warp Website / Registration Form Design

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpServer#18]
We need a better Registration form and stuff then the Plain HTML Placeholder.

**Comment by Amaikokonut** [comment]
Some stuff we should maybe consider for the site:

- Writing a set of guidelines/what to expect for the warp that basically says stuff like don't bully/harass people, don't use the software for malicious purposes, don't make scripts that just generate endless DMAs, if you're going to develop/test stuff and are afraid that it might stress the server, get in touch with an admin who can be online and reboot the server in case something breaks, etc.
- Do we need to have any legal disclaimers like 'we can't be held liable if someone does find a way to abuse the software and send a billion DMAs and ruins your world, we can't be held liable if the software messes up your computer in any way, etc'?
- Since we're collecting email addresses (which are considered to be personal information) do we need a privacy policy to legally cover our butts? At the very least we should probably require new registrants to check a box confirming they are 13+ years old to comply with COPPA?

**Comment by KeyboardInterrupt** [comment]
Legal Compliance stuff... Urgh you are probably right XD
Yea we should add some disclaimer Text to the Registration Form ^^
Guidelines are also a good Idea!

**Comment by KeyboardInterrupt** [comment]
Okay, So i added a Checkbox to let a user that registers for an account tick off that they are at least 13 Years old, and another Box to tick of that states that they have read and accepted the TOS / Privacy Policy.

Problem is, we don't have a TOS and Privacy Policy yet. :disappointed: .

I don't know how "legal stuffy" we need to become.

Things I think the TOS should contain are the necessary phrases, so we wont be held liable for whatever happens to those using the Albian Warp, Their Data or whatever XD..
Also I would like to state that we cannot be held liable for whatever content users decide to share via Albian Warp.
Also that we will reserve the right to delete whatever displeases us and Ban users that involve in that stuff, (Hate speech, pornography, Gore, Religious, Political Discussions, Copyright Foo, Spam, abusive behavior)

The Privacy Policy should state which data we collect and why we do so i.E. what we use your email for, what will happen to DMA's, RTDMA's and Creatures sent via Albian Warp.

In general I would like to keep the Data collection to a minimum and state so in the Privacy Policy.
Also I would like to provide a simple option for Users to delete their Account without any trace left in the Database, (Messages, DMA's and everything related to them will be deleted as well!)
Server Logs generated by the Webserver will be anonymized so we cannot use them to pin down who exactly is using the Website/API. in general I want to keep the verbosity of the logs on a minimal lvl and don't want to log anything that is not necessary.
The Server software itself will eventually keep track of certain actions like sending creatures and Messages, but those events should only be used for statistical/analytics questions to resolve just simple questions like "how many creatures has user X warped", "how many messages where sent by the user." "how many messages of what `type` where sent"

To apply to silly laws we should also put up one of those Cookie warning banners on the Webinterface once a Login is possible! :cookie:.


To be on the "saver" side of things we would also need a clause stating that the TOS might change, and that Users schould check every now and then. and that a new TOS will become effective within 30 days.

Okay so did I miss anything?
I guess it does not need to be perfect right of the start, and we will eventually come up with a Code and certain rules.

**Comment by KeyboardInterrupt** [comment]
Also a document stating the etiquette, like dont be an arse, dont harras people and stuff like this, should be added.
So essentially we need three Docs.

- General Rules
 - Dont be an arse
- TOS
 - We are not liable for whatever you do, with Albian Warp or what our users do!
- Privacy Policy
 - State what data we collect and what we use it for (minimum needed and as transparent as posible)
